# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Muhammad Hamza
title: Software Engineer
email: hamzaquant@gmail.com
mobile: +447955290709
#website: mhamza.one

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: hamza3256
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: -muhammadhamza
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Resume
    icon: fa-adobe
    url: https://drive.google.com/file/d/1t5o-ufZ44zwsXpcCkFJ5-OOI58KyWchp/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hamza and I'm a computer science graduate from Queen Mary University of London with a 1st class.
  
  As a highly adaptable and competent software engineer, I am proficient in Python, Java, and frontend languages and frameworks (HTML, CSS, JavaScript, React) with varying experiences in MongoDb, Django, MySQL, and C#.
  
  I have a keen interest in software engineering and I'm enthused by the prospect of becoming a part of such a dynamic and stimulating field. I am confident the skills and determination that have brought me success in the past would stand me in good stead for the exciting challenges ahead.
  

content:

 - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Queen Mary University of London
        caption: 2017 - 2020
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

 - title: Technical Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MThree
        link: mthree.com
        # link_text: boringcompany.com
        sub_title: Alumni Software Engineer
        caption: October 2020 - Present
        description: # this will include new lines to allow paragraphs
          layout: list
          content:
           - Underwent six weeks training in Full Stack Engineering (Java).

      - layout: left
        title: Freelance
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: June 2020 - August 2020
        description: # this will include new lines to allow paragraphs
          layout: list
          content:
            - Created separate and restricted admin access for inventory management.
            - Implemented different access levels to handle orders and customer interaction which sped up the payment process by 70%.
      
 
  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: XBorder
        link: xborder.herokuapp.com
        # link_text: Project Website
        additional_links:
          - title: hamza3256/xborder
            icon: fab fa-github
            url: github.com/hamza3256/xborder
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description:
          layout: list
          content:
            - "Designed and developed a web application for cross‑border transactions as part of my final year project."
            - Implemented and deployed smart contracts which enables a user to perform transactions using escrow account implementation.
            - Deployed functions on AWS that fetches live data from Binance using API.
            - "Technologies used: <mark>Solidity</mark>, Ethereum smart contracts, ReactJS."
 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
