# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/MyProf.jpg

# Personal info
name: Muhammad Hamza
title: Software Engineer
email: hamzaquant@gmail.com
mobile: +447955290709
#website: mhamza.one

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: hamza3256
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: -muhammadhamza
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Resume
    icon: fa-adobe
    url: https://drive.google.com/file/d/1t5o-ufZ44zwsXpcCkFJ5-OOI58KyWchp/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/MyProf.jpg
about_content: | # this will include new lines to allow paragraphs


  Hi, my name's Hamza and I'm a computer science graduate from Queen Mary University of London with a 1st class.

  As a highly adaptable and competent software engineer, I am proficient in Python, Java, and frontend languages and frameworks (HTML, CSS, JavaScript, React) with varying experiences in MongoDb, Django, MySQL, and C#.

  I have a keen interest in software engineering and I'm enthused by the prospect of becoming a part of such a dynamic and stimulating field. I am confident the skills and determination that have brought me success in the past would stand me in good stead for the exciting challenges ahead.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Technical Skills**

  - Proficient in <mark>Python</mark>, <mark>Java</mark>, <mark>JavaScript</mark>
  - Varying experience with <mark>C#</mark>, <mark>React</mark>, <mark>MySQL</mark>, <mark>MongoDB</mark>, <mark>NodeJS</mark>, <mark>HTML/CSS</mark>, <mark>Django</mark>
  - Experienced with Git, Unity3D, Windows, Linux, Hadoop, Apache Spark

  **Acheivements**
  - Achieved top 50 placement in Global Coding Challenge - Credit Suisse (October 2019)
  - Deputy Principal's Award for academic excellence at Heriot-Watt University (July 2018)
  - Copper award in Cambridge Chemistry Challenge (June 2015)

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
